# Generated by Django 3.1.2 on 2021-10-28 02:25

import ckeditor.fields
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apply', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(max_length=200)),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='learn/')),
                ('about_tag', models.CharField(default='project!', max_length=255)),
                ('author', models.CharField(default='microsecond!', max_length=255, verbose_name=django.contrib.auth.models.User)),
                ('body', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('post_date', models.DateField(auto_now_add=True)),
                ('snippet', models.CharField(default='Click Link to write more details...', max_length=255)),
                ('likes', models.ManyToManyField(related_name='ablog_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
