# Generated by Django 3.1.2 on 2021-10-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0002_auto_20211025_0500'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='playstore_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
